### PR TITLE
Regs to memory

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
This seems to result in 82 witness columns.

**Comment by leonardoalt** [comment]
> This seems to result in 82 witness columns instead of 130.

in what example?

Currently this is what I get when running powdr-riscv on revm:

`This seems to result in 82 witness columns instead of 130.`

**Comment by leonardoalt** [comment]
@chriseth how far was this from ready?

**Comment by leonardoalt** [comment]
Closing in favor of the new approach.

**Pull request closed without merging**
