### PR TITLE
Multiplication returning both high and low bits.

### PR DESCRIPTION
**Pull request by lvella**
Makes use of multi-return.

### CODE REVIEW

**Review by leonardoalt — APPROVED** [review]

**Comment by leonardoalt** [comment]
Actually @georgwiese pointed out these constraints are not sounds due to overflow

**Comment by leonardoalt** [comment]
or actually, it is sounds as long as the assumption that Z and W are 32 bits is correct

**Comment by lvella** [comment]
> Actually @georgwiese pointed out these constraints are not sounds due to overflow

How? If both inputs are 0 <= x < 2**32, the maximum possible result is 0xfffffffe00000001, which is smaller than the Goldilocks field characteristic of 0xffffffff00000001.

**Comment by leonardoalt** [comment]
yea, we should eventually do a pass checking whether everything is properly wrapped

**Comment by lvella** [comment]
> or actually, it is sounds as long as the assumption that Z and W are 32 bits is correct

Well, then we have to prove that every instruction always leave something u32 in the registers.

**Comment by leonardoalt** [comment]
Groebner Basis activated

**Pull request merged**
