### PR TITLE
Use permutations to connect machines in RISC-V VM

### PR DESCRIPTION
**Pull request by georgwiese**
Depends on #1154.

This should be cheaper to prove!

### CODE REVIEW

**Comment by leonardoalt** [comment]
Nice! Will approve after the dependency PR is merged

**Comment by georgwiese** [comment]
I'm also planning to run some benchmarks tomorrow!

**Review by leonardoalt — APPROVED** [review]

**Comment by leonardoalt** [comment]
This needs another merge from main and conflict resolution

**Comment by chriseth** [comment]
15 commits and that's the diff?

**Review by chriseth — APPROVED** [review]

**Comment by georgwiese** [comment]
Yes because it was building on another PR that got merged in the meantime.

**Comment by georgwiese** [comment]
Late Benchmark: To prove the Kaccak example, proving time using eStark imporves from 73s to 68s.

**Comment by leonardoalt** [comment]
Nice!

**Pull request merged**
