### PR TITLE
Make Pipeline Clonable

### PR DESCRIPTION
**Pull request by georgwiese**
Benchmark result (relevant because query callback now lives in an `Arc` instead of `Box`):
```
executor-benchmark/keccak
                        time:   [12.424 s 12.939 s 13.524 s]
                        change: [-9.7680% -4.4556% +1.4262%] (p = 0.16 > 0.05)
                        No change in performance detected.

executor-benchmark/many_chunks_chunk_0
                        time:   [47.732 s 48.429 s 49.229 s]
                        change: [+0.7940% +2.8040% +4.9215%] (p = 0.02 < 0.05)
                        Change within noise threshold.
```

### CODE REVIEW

**Comment by chriseth** [comment]
Where is this used?

**Comment by georgwiese** [comment]
It's not used yet, but it would be helpful in any situation where you want to run part of the pipeline several times (with different arguments). A prime example is continuations. [Here](https://github.com/powdr-labs/powdr/blob/main/riscv/src/continuations.rs#L48), we could get rid of that "pipeline factory" business and just take a pipeline, advance it to whatever stage we want to start from, and then clone and run for each chunk.

**Comment by chriseth** [comment]
I'm fine with this if it is helpful.

**Comment by georgwiese** [comment]
Let's merge it, there isn't really any downside as far as I can see.

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
