### PR TITLE
Updating to latest riscv-executor branch.

### PR DESCRIPTION
**Pull request by lvella**

### CODE REVIEW

**Comment by leonardoalt** [comment]
maybe both branches should rebase on main before this? looks like a massive diff

**Comment by lvella** [comment]
Eventually, when either is about to merge, yes.

A quarta, 22/11/2023, 16:55, Leo ***@***.***> escreveu:

**Comment by leonardoalt** [comment]
But what is this diff then? It has a lot of stuff from main. If both braches rebased on main this would be much smaller

**Comment by lvella** [comment]
This PR is a merge from main + riscv-executor into Georg's continuation
branch, that is why it is big.

I prefer to rebase/squash/whatever just when we are about to merge into
main, just because it is much easier to handle merges than rebases.

A quarta, 22/11/2023, 22:56, Leo ***@***.***> escreveu:

**Pull request closed without merging**
