### PR TITLE
add estark-polygon as features of other crates

### PR DESCRIPTION
**Pull request by leonardoalt**

### CODE REVIEW

**Comment by lvella** [comment]
Lets have an approval on #1211 before rebasing and merging this one.

**Comment by leonardoalt** [comment]
I was going to approve it earlier but I didn't because it was missing these lol

**Comment by lvella** [comment]
I'll cherry pick this commit after I squash the other. I must squash the other, right?

**Comment by leonardoalt** [comment]
Don't have to, since we have auto-squash now at merge time. So also no need to cherry pick this commit, can also merge this PR as is and then squash the other one when ready to merge

**Pull request merged**
