### PR TITLE
fix pipeline callback chain

### PR DESCRIPTION
**Pull request by leonardoalt**

### CODE REVIEW

**Review by pacheco — COMMENTED** [review]
Couldn't query QueryCallback return just `Result<T>` instead of `Result<Option<T>>`?
Doesn't seem like there's any situation where `Ok(None)` is returned.

**Comment by leonardoalt** [comment]
I'd prefer to keep the changes minimal in this PR, since changing the type will affect more places. We can re-consider whether `Ok(None)` is useful later on

**Review by pacheco — APPROVED** [review]
Ok, can you make an issue for it?

**Comment by leonardoalt** [comment]
Done: https://github.com/powdr-labs/powdr/issues/1314

**Pull request merged**
