### PR TITLE
Specialized code for goldilocks.

### PR DESCRIPTION
**Pull request by chriseth**
This is mostly a reduced copy of the goldilocks implementation we already have with the main difference that the division tries to perform integer division first if it can be done without remainder.

### CODE REVIEW

**Review by georgwiese — COMMENTED** [review]
Hmm, do we have any plan how can avoid this code duplication? Also, if it is useful to attempt integer division in one implementation, why is it not in the other?

**Comment by georgwiese** [comment]
But would it be possible to use this implementation in the other one?

**Comment by chriseth** [comment]
It is missing some parts that we use there. I think the best way would be to create a new crate, but maybe let's do that when we have some more time?

**Review by georgwiese — APPROVED** [review]
ok

**Pull request merged**
