### PR TITLE
Arbitrary Block Machine Lookup

### PR DESCRIPTION
**Pull request by georgwiese**

### CODE REVIEW

**Comment by Schaeff** [comment]
@georgwiese is this PR still needed?

**Comment by Schaeff** [comment]
(wrong button my bad!)

**Comment by georgwiese** [comment]
It's a bit abandoned, but I think it's still relevant. If I remember correctly the goal is to fix the `vm_to_block_multiple_interfaces` test!

**Comment by leonardoalt** [comment]
> It's a bit abandoned, but I think it's still relevant. If I remember correctly the goal is to fix the `vm_to_block_multiple_interfaces` test!

@georgwiese is this still the case?

**Comment by leonardoalt** [comment]
@georgwiese will finish this

**Comment by georgwiese** [comment]
OK, OK, fine. Will do here: #822

**Pull request closed without merging**
