### PR TITLE
Support arrays of intermediates

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by leonardoalt** [comment]
conflicts

**Comment by leonardoalt** [comment]
can you rebase it on top of https://github.com/powdr-labs/powdr/pull/979 and change the base? it's gonna be easier to review

**Comment by chriseth** [comment]
phew, it is working!

**Review by leonardoalt — COMMENTED** [review]
I'm somewhat surprised this "just works" lol

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
