### PR TITLE
Set `target-cpu=native` compiler flag

### PR DESCRIPTION
**Pull request by georgwiese**
This makes sure that we use AVX instructions when available. Seems to speed up Plonky3 proofs (slightly for Goldilocks and 30-50% for BabyBear).

### CODE REVIEW

**Review by leonardoalt — APPROVED** [review]
Looks good, but do you know if it has any bad consequences otherwise?

**Comment by chriseth** [comment]
I guess we shouldn't publish it like that, because it won't run on other CPUs

**Comment by chriseth** [comment]
Publish as a binary that is.

**Comment by georgwiese** [comment]
Yeah, AFAIK the only downside would be reduced portability. I think we're talking about building the tests on our server and running it on GitHub, right? Maybe that would be a problem?

But I think we could merge and keep this in mind if we encounter any issues.

**Comment by chriseth** [comment]
I mean at some point we have to think about how to publish powdr as a binary and not just a rust crate, so it's not only about the tests.

**Comment by georgwiese** [comment]
We can also configure this flag to active in some profiles, and create a `native` profile that should be used for maximum performance. But I feel like if you download the build from somewhere, you want the maximum performance, no?

**Comment by georgwiese** [comment]
Hmm, after merging `main`, the tests fail. That's probably because the build happens on a different machine now?

**Comment by georgwiese** [comment]
Closed in favor of #1766

**Pull request closed without merging**
