### PR TITLE
Add benchmark for JITgen

### PR DESCRIPTION
**Pull request by georgwiese**
Adds the benchmark I used for measuring the witness generation JIT in #2242.

### CODE REVIEW

**Comment by georgwiese** [comment]
Maybe it's late, but I don't know how to run this:
```
$ cargo bench --bench jit_witgen_benchmark
    Finished `bench` profile [optimized] target(s) in 0.48s
warning: the following packages contain code that will be rejected by a future version of Rust: mathru v0.6.10
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running benches/jit_witgen_benchmark.rs (target/release/deps/jit_witgen_benchmark-a4f413cc0aba77fb)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by pacheco** [comment]
i think you have to add the bench to toml: check `riscv/Cargo.toml` for `executor_benchmark`

**Comment by georgwiese** [comment]
That worked, thanks!

**Comment by georgwiese** [comment]
Example run:
`POWDR_JIT_OPT_LEVEL=1 cargo bench -p powdr-pipeline --bench jit_witgen_benchmark`

On my machine, one iteration takes around 12.5s.

However, it seems like in CI, this is closer to 55s. On our server, the time for one iteration is around 62s.

**Review by Schaeff — APPROVED** [review]
made it to https://docs.powdr.org/dev/bench/ 👍

**Pull request merged**
