### PR TITLE
Instruction tests properly returning from __runtime_start.

### PR DESCRIPTION
**Pull request by lvella**
It seems #752 actually broke instruction tests, and this is my attempt to fix it.

### CODE REVIEW

**Comment by chriseth** [comment]
Can you explain what this does?

**Comment by leonardoalt** [comment]
> Can you explain what this does?

the main change is the `.h` file.
Before it had the infinite loop we used to require, but that's not needed anymore and causes problems for the executor. The pass behavior should be to just end execution without fails

**Comment by lvella** [comment]
> Can you explain what this does?

In #752 I removed the infinite loop reached at the end of a successful instruction tests. Instead, I tried to simply return from `__runtime_start`. This makes a difference for the executor, as the tests would actually terminate.

Turns out that some tests rewrites the `ra` register, breaking `ret`. In this PR I fix my initial attempt, by saving the return address in the memory location `__return_pointer` before executing the test, and loading it back before `ret`ing,

**Comment by lvella** [comment]
`lb` and `lbu` are failing now. Do you know why this new entry in the data section would upset them? Shouldn't affect the alignment, right?

**Comment by lvella** [comment]
I think `lrsc` is broken, but has been broken for a long time now.

**Comment by lvella** [comment]
Yep just tested locally and `lrsc` was broken since before #752. I think this can be merged as is.

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
