### PR TITLE
Pinning git dependencies to git revision.

### PR DESCRIPTION
**Pull request by lvella**
Tag is also acceptable. Branch is not.

Solves #1914

### CODE REVIEW

**Review by leonardoalt — COMMENTED** [review]
Why draft?

**Comment by lvella** [comment]
I don't know how the other PRs, of the dependencies, will merge. If they are squashed into new commits, this one must be updated. If they are just merged or fast-forwarded, this PR is fine.

**Comment by lvella** [comment]
Please approve these first:
https://github.com/powdr-labs/halo2wrong/pull/1
https://github.com/powdr-labs/snark-verifier/pull/1
https://github.com/powdr-labs/halo2-solidity-verifier/pull/1

**Comment by leonardoalt** [comment]
done

**Comment by lvella** [comment]
I checked, and the commit hashes are still valid after the deps have been merged. This PR is good to go.

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
