### PR TITLE
clippy happy

### PR DESCRIPTION
**Pull request by leonardoalt**

### CODE REVIEW

**Review by georgwiese — APPROVED** [review]
Clippy: 😄

**Comment by georgwiese** [comment]
Just wondering, if that's a clippy error, why is the CI green on `main`? Also, if I run clippy on `main` manually, I don't find it and when I run `cargo clippy --tests` I find a redundant import on `powdr_cli/src/main.rs:521:5`.

**Comment by Schaeff** [comment]
I suspect different rust versions on CI and locally which have different clippy versions.

**Comment by leonardoalt** [comment]
> Just wondering, if that's a clippy error, why is the CI green on `main`? Also, if I run clippy on `main` manually, I don't find it and when I run `cargo clippy --tests` I find a redundant import on `powdr_cli/src/main.rs:521:5`.

yea this one I also only see when running `cargo test --all`

**Pull request merged**
